services:
    db:
        image: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: example
            MARIADB_DATABASE: blog
        volumes:
            - ta22vdbdata:/var/lib/mysql
        ports:
            - 3307:3306
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - 1025:1025
            - 8025:8025
volumes:
    ta22vdbdata:
